import Link from 'next/link';
import Head from 'next/head';
import Layout, { siteTitle } from '../../components/layout';

export default function FirstPost() {
  return (
    <Layout test>
      <Head>
        <title>しろ</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta property='' />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <h1>First post</h1>
      <Link href="/">
        <a>Back to Home</a>
      </Link>
    </Layout>
  )
}